raspicam_node: {ISO: 400, awb_gains: '(2.0,2.0)', awb_mode: 'off', brightness: 50,
  camera_frame_id: raspicam, camera_id: 0, camera_info_url: 'package://raspicam_node/camera_info/camerav2_1280x960.yaml',
  camera_name: camerav2_1280x960, contrast: 0, enable_imv: false, enable_raw: true,
  exposure_compensation: 0, exposure_mode: auto, framerate: 1, hFlip: false, height: 960,
  private_topics: false, saturation: 0, sharpness: 0, shutter_speed: 0, vFlip: false,
  video_stabilisation: false, width: 1280, zoom: 1.0}
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_ubiquityrobot__34341: 'http://ubiquityrobot:34341/', host_ubiquityrobot_local__46201: 'http://ubiquityrobot.local:46201/'}
rosversion: '1.12.13

  '
run_id: 1b040112-78ce-11e9-951f-b827eb1b635f
